[package]
name = "memtest"
description = "A library for detecting faulty memory"
version = "0.2.0"
authors = ["Brian Tsoi <brian.s.tsoi@gmail.com>"]
edition = "2021"
license = "MPL-2.0"
homepage = "https://github.com/mozilla/memtest"
repository = "https://github.com/mozilla/memtest"
keywords = ["memory", "stability"]
readme = "README.md"

[dependencies]
anyhow = "1.0.69"
num_cpus = "1.16.0"
rand = {version = "0.8.5", features = ["small_rng"]}
serde = {version = "1.0.214", features = ["derive"]}
serde_json = "1.0.116"
tracing = "0.1.37"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58.0", features = [
    "Win32_Foundation",
    "Win32_System_Memory",
    "Win32_System_SystemInformation", 
    "Win32_System_Threading",
] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.158"

[dev-dependencies]
tracing-subscriber = "0.3.18"
