[package]
name = "rust-memtester"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.0"
rand = "0.8.4"
region = "3.0.2"
windows = { version = "0.58.0", features = ["Win32_System_Threading"] }    
anyhow = "1.0"
tracing = "0.1.37"
