[package]
name = "rust-memtester"
version = "0.1.0"
edition = "2021"

[dependencies]
region = "3.0.2"
rand = "0.8.4"
    
[dependencies.windows]
version = "0.58.0"
features = [
    "Data_Xml_Dom",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_System_Memory",
    "Win32_UI_WindowsAndMessaging",
]

