[package]
name = "rust-memtester"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.0"
rand = "0.8.4"
region = "3.0.2"
anyhow = "1.0"
tracing = "0.1.40"

[dependencies.windows]
version = "0.58.0"
features = [
  "Win32_Foundation",
  "Win32_System_Memory",
  "Win32_System_SystemInformation", 
  "Win32_System_Threading",
]    

[dev-dependencies]
tracing-subscriber = "0.3.18"
